### ISSUE TITLE
Segfault when installing girder-utm

### ISSUE THREAD

**Issue by subdavis** [zachmullen/girder-utm#3]
```
...
Building wheels for collected packages: girder, girder-jobs, dogpile.cache, psutil                                                               │
  Running setup.py bdist_wheel for girder ... done                                                                                               │
  Stored in directory: /home/brandon/.cache/pip/wheels/df/70/4c/64cd97d636f2fc769dc966a97b0689d6e10d66a92f6753a853                               │
  Running setup.py bdist_wheel for girder-jobs ... done                                                                                          │
  Stored in directory: /home/brandon/.cache/pip/wheels/b9/8d/71/6006b867b959af6486613d45650d88128c268aaef8d79d86a2                               │
  Running setup.py bdist_wheel for dogpile.cache ... done                                                                                        │
  Stored in directory: /home/brandon/.cache/pip/wheels/13/72/54/655c2958a0664e32f91c1c49dec9e9cb67acc1a2829d2e1931                               │
  Running setup.py bdist_wheel for psutil ... done                                                                                               │
  Stored in directory: /home/brandon/.cache/pip/wheels/d2/71/40/9c6993129f8cda369d0f21c46a13a6adab7fb1664fe6512551                               │
Successfully built girder girder-jobs dogpile.cache psutil                                                                                       │
Installing collected packages: jmespath, docutils, urllib3, six, python-dateutil, botocore, s3transfer, boto3, backports.functools-lru-cache, mor│
e-itertools, cheroot, pytz, jaraco.functools, tempora, portend, CherryPy, click, click-plugins, dogpile.cache, filelock, jsonschema, MarkupSafe, │
Mako, pycparser, cffi, bcrypt, idna, asn1crypto, cryptography, passlib, pymongo, PyYAML, psutil, pyOpenSSL, certifi, chardet, requests, girder, g│
irder-jobs, billiard, vine, amqp, kombu, celery, setuptools-scm, jsonpickle, requests-toolbelt, diskcache, girder-client, girder-worker-utils, de│
corator, networkx, pbr, stevedore, docker-pycreds, websocket-client, docker, girder-worker, girder-utm                                           │
  Running setup.py develop for girder-utm                                                                                                        │
Segmentation fault (core dumped)
```

After a failed installation, everything works except for the UTM run.  

POST /utm causes:

```
[2018-11-29 11:27:50,111] ERROR: An error occurred in girder_before_task_publish.                                                                │
Traceback (most recent call last):                                                                                                               │
  File "/home/brandon/venvs/girder/lib/python3.6/site-packages/girder_worker/app.py", line 60, in girder_before_task_publish                     │
    retry_policy=retry_policy, **kwargs)                                                                                                         │
  File "/home/brandon/venvs/girder/lib/python3.6/site-packages/girder_worker/context/girder_context.py", line 11, in create_task_job             │
    from girder.plugins.worker import utils                                                                                                      │
ModuleNotFoundError: No module named 'girder.plugins'
```

@kotfic, @zachmullen do you know of any pitfalls when installing girder_worker or any of those other packages?  Thanks.

**Comment by zachmullen** [comment]
It looks like you are running an old version of girder_worker, maybe the latest "stable" release (which is ancient). It might be easiest to install the worker from master instead.

No idea why the segault is happening... seems like something wrong with your underlying python environment?

**Comment by subdavis** [comment]
Upgrading girder and girder-worker seems to have done the trick.  Thanks.
